development:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: rails_bootstrap_development
  pool: 5
  username: postgres
  password: postgres

test:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: rails_bootstrap_test
  pool: 5s
  username: postgres
  password: postgres

production:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: rails_bootstrap_production
  pool: 5
  username: postgres
  password: postgres